{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-flask-app-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-flask-app-service
                port:
                  number: 80
          - path: "/pods"
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-flask-app-service
                port:
                  number: 80
{{- end }}